version: '2.2'
services:

  # Nginx proxy kibana
  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8080:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - PROXY_PASS=http://kibana:5601/
    networks:
      - esnet-1

  # Nginx proxy elasticHQ
  nginx2:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8081:80
      - 8091:8090
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - PROXY_PASS=http://elasticsearchHq:5000/
    networks:
      - esnet

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster-elk
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data-volumn/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet-1

  # Elasticsearch2
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster-elk
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data-volumn/esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet-1

  # Elasticsearch3
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster-elk
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data-volumn/esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet-1

  # Kibana
  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.8'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - esnet-1

  # Elasticsearch HQ
#  elasticsearchHq:
#    image: elastichq/elasticsearch-hq
#    container_name: elasticsearchHq
#    ports:
#      - ${ES_HQ}:5000
#    networks:
#      - esnet

  # headPlugin
#  headPlugin:
#    image: 'mobz/elasticsearch-head:5'
#    container_name: head
#    ports:
#      - '9100:9100'
#    networks:
#      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet-1:
